export function getRandomName() {
  const namesList = [
    'Alice',
    'Bob',
    'Charlie',
    'David',
    'Eve',
    'Frank',
    'Grace',
    'Hannah',
    'Ivy',
    'Jack',
    'Kathy',
    'Liam',
    'Mona',
    'Nina',
    'Oscar',
    'Paul',
    'Quinn',
    'Rita',
    'Sam',
    'Tina',
    'Uma',
    'Victor',
    'Wendy',
    'Xander',
    'Yara',
    'Zane',
    'Amy',
    'Brian',
    'Clara',
    'Derek',
    'Elena',
    'Felix',
    'Gina',
    'Harry',
    'Isla',
    'Jacob',
    'Kira',
    'Leo',
    'Mia',
    'Noah',
    'Olivia',
    'Penny',
    'Quincy',
    'Ryan',
    'Sophia',
    'Tom',
    'Ursula',
    'Vince',
    'Will',
    'Xena',
    'Yasmine',
    'Zack',
    'Aaron',
    'Bella',
    'Caleb',
    'Dana',
    'Ethan',
    'Fiona',
    'George',
    'Holly',
    'Ian',
    'Jade',
    'Kyle',
    'Laura',
    'Max',
    'Nate',
    'Opal',
    'Pete',
    'Quinn',
    'Rachel',
    'Steve',
    'Tracy',
    'Ulysses',
    'Val',
    'Wade',
    'Xiomara',
    'Yvonne',
    'Zoe',
    'Aiden',
    'Brooke',
    'Cody',
    'Diana',
    'Elliot',
    'Faith',
    'Gavin',
    'Hope',
    'Isaac',
    'Jill',
    'Kevin',
    'Lily',
    'Mason',
    'Nora',
    'Owen',
    'Paula',
    'Quentin',
    'Ruby',
    'Sean',
  ];
  return namesList[Math.floor(Math.random() * namesList.length)];
}

export function getRandomComment() {
  const commentsList = [
    'This video was exactly what I needed today!',
    'Amazing content, keep it up!',
    'I’ve learned so much from this, thank you!',
    'This deserves way more views!',
    'Your editing skills are top-notch! 🎥',
    'Who else is binge-watching this channel?',
    'Can’t wait for the next video! 😊',
    'This was so inspiring, thank you!',
    'You explain things so clearly! 👌',
    'This made my day!',
    'Love the positive vibes in this video!',
    'This should have gone viral! 🚀',
    'I never knew I needed this video until now!',
    'The visuals are stunning! 😍',
    'You’ve gained a new subscriber! 🛎️',
    'This is one of the best videos I’ve seen on this topic!',
    'You made it so easy to understand!',
    'This is the quality content I signed up for!',
    'I appreciate all the hard work that went into this!',
    'This video just blew my mind! 🤯',
    'The production value on this is incredible!',
    'I love your enthusiasm! ⚡',
    'This video was so entertaining!',
    'This deserves all the likes!',
    'Can we talk about how great the music is? 🎶',
    'I’ve been waiting for this video all week!',
    'I’m definitely sharing this with my friends! 😊',
    'This is exactly what I was looking for!',
    'I’m hooked on your content! 😍',
    'This is seriously underrated!',
    'You just got a new fan!',
    'This is pure gold! 💛',
    'The pacing of this video is perfect!',
    'You’ve really outdone yourself this time! 👏',
    'I could watch this all day!',
    'This video should be in everyone’s recommended!',
    'You never disappoint!',
    'This was so satisfying to watch! 😌',
    'I wish I found this channel sooner!',
    'This is my new favorite video!',
    'I didn’t know I needed this until now! 😊',
    'This deserves an award! 🏆',
    'The content you create is just amazing!',
    'This video is so well put together!',
    'You made my day with this upload! 🌟',
    'I can’t get enough of your videos!',
    'This was exactly what I needed to see!',
    'Your channel is a hidden gem!',
    'This is the best thing I’ve seen all day! 😄',
    'I’m loving the creativity here! 🎨',
  ];
  return commentsList[Math.floor(Math.random() * commentsList.length)];
}
